version: 2

jobs:
  lint:
    docker:
      - image: ubuntu:19.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U black flake8
      - run: LC_ALL=C.UTF-8 black --check setup.py pygalmesh/ test/*.py
      - run: flake8 setup.py pygalmesh/ test/*.py
  build:
    working_directory: ~/pygalmesh
    docker:
      - image: ubuntu:19.04
    steps:
      - run: apt-get update
      - run: apt-get install -y libcgal-dev libeigen3-dev python3-pip clang
      - run: pip3 install -U pytest pytest-cov pybind11 lxml
      - checkout
      # install
      # Use clang++ for its smaller memory footprint.
      - run: CC="clang++" pip3 install .
      # The actual test
      - run: cd test/ && pytest

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
